services:
  - type: web
    name: crotalia-app
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn Crotalia.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8