# Generated by Django 6.0.7 on 2026-07-22 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Granja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Granja')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilGanadero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='ganaderia.granja')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_casa', models.CharField(max_length=10, verbose_name='Nº Casa')),
                ('crotal', models.CharField(max_length=14, unique=True, verbose_name='Crotal')),
                ('nombre_padre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Padre')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('granja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacas', to='ganaderia.granja', verbose_name='Granja')),
                ('madre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijas', to='ganaderia.vaca', verbose_name='Madre')),
            ],
            options={
                'unique_together': {('granja', 'numero_casa')},
            },
        ),
        migrations.CreateModel(
            name='Parto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_real', models.DateField(verbose_name='Fecha Real del Parto')),
                ('nombre_padre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Padre')),
                ('genero_cria', models.CharField(choices=[('MACHO', 'Macho'), ('HEMBRA', 'Hembra')], max_length=10, verbose_name='Género de la Cría')),
                ('numero_casa_cria', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nº Casa de la Cría (Solo hembras)')),
                ('madre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partos', to='ganaderia.vaca', verbose_name='Madre (Nº Casa)')),
            ],
        ),
        migrations.CreateModel(
            name='Inseminacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Inseminación')),
                ('toro', models.CharField(max_length=100, verbose_name='Nombre del Toro')),
                ('estado', models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo'), ('DUDOSO', 'Dudoso')], default='DUDOSO', max_length=10, verbose_name='Estado')),
                ('estimacion_secado', models.DateField(blank=True, null=True, verbose_name='Estimación de Secado')),
                ('estimacion_parto', models.DateField(blank=True, null=True, verbose_name='Estimación de Parto')),
                ('vaca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inseminaciones', to='ganaderia.vaca', verbose_name='Vaca (Nº Casa)')),
            ],
        ),
    ]
